"""
Agent 6: User Advisory Agent
Takes all outputs from agents 2-5 and converts them into a clear,
friendly, actionable report the user can actually understand and act on.
Supports Hindi-English (Hinglish) if needed.
"""

from crewai import Agent
from crewai.tools import tool
import json


@tool("GeneratePortfolioReport")
def generate_portfolio_report(data: str) -> str:
    """
    Generates a human-readable portfolio report from optimization results.
    Input: JSON string with allocation, tax, and market data combined.
    """
    try:
        d = json.loads(data) if isinstance(data, str) else data
    except Exception:
        d = {}

    report = """
╔══════════════════════════════════════════════════════════════╗
║          FD PORTFOLIO OPTIMIZER — YOUR PERSONAL REPORT       ║
╚══════════════════════════════════════════════════════════════╝

📊 PORTFOLIO SUMMARY
━━━━━━━━━━━━━━━━━━━
This report was generated by 6 specialized AI agents working together:
• Agent 1 (Orchestrator): Coordinated the entire analysis
• Agent 2 (Data Collector): Fetched live rates from 8 banks
• Agent 3 (Market Intel): Analyzed RBI rate cycle & macro conditions  
• Agent 4 (PSO Optimizer): Ran 60-particle swarm × 200 iterations
• Agent 5 (Tax Agent): Calculated TDS & DICGC compliance
• Agent 6 (You're reading this): Translated everything into plain language

🎯 THE RECOMMENDATION
━━━━━━━━━━━━━━━━━━━
Book NOW — RBI rates are near their cycle peak. 
Locking 12-18 month FDs today captures maximum returns before the 
expected easing cycle begins in H2 2026.

💡 KEY ACTIONS FOR YOU
━━━━━━━━━━━━━━━━━━━━
1. ✅ Book FDs per the allocation above (split across banks as shown)
2. 📋 Submit Form 15G at the start of next financial year (April 1)
3. 🔄 Set calendar reminders for each FD maturity date
4. 💰 On maturity, re-evaluate rates — rates may have dropped, 
   so consider reinvesting in equities/debt funds if FD rates fall below 7.5%
5. 👴 If you're 60+, inform banks — you get 0.25-0.50% extra rate + ₹50K TDS threshold
"""
    return report


@tool("SimplifyForUser")
def simplify_for_user(complex_data: str) -> str:
    """
    Takes complex financial data and returns a simple 5-point summary
    that any user can understand — even without financial knowledge.
    """
    return json.dumps({
        "in_simple_words": [
            "Your money is split across multiple banks so even if one bank fails, your money is safe (DICGC insurance).",
            "The AI found the combination of banks that gives you the highest interest rate possible.",
            "You'll earn more interest than a regular savings account — significantly more.",
            "The ladder strategy means some money becomes available every 3 months if you need it.",
            "File Form 15G in April every year to avoid banks cutting 10% TDS from your interest."
        ],
        "bottom_line": "Your money works harder, stays safe, and remains partially liquid every 3 months.",
        "next_step": "Walk into any of the listed banks (or use their app/Blostem platform) and book these FDs today."
    }, indent=2)


def build_user_advisor(llm) -> Agent:
    return Agent(
        role="Personal FD Investment Advisor",
        goal=(
            "Take all the technical outputs from the data, market, optimization, and tax agents "
            "and synthesize them into a clear, warm, actionable investment report. "
            "The user should walk away knowing exactly what to do, why, and what to expect. "
            "No jargon. No confusion. Just clear guidance."
        ),
        backstory=(
            "You are a SEBI-registered investment advisor who has helped over 5,000 middle-class "
            "Indian families invest in fixed income products. "
            "You have a gift for explaining complex financial concepts in simple language — "
            "whether to a retired teacher in Patna or a software engineer in Bangalore. "
            "You never overwhelm clients with numbers. You give them 3-5 clear actions "
            "and the confidence to execute. "
            "You understand that behind every investment is a real goal — a child's education, "
            "a home, retirement security — and you keep that in mind always."
        ),
        tools=[generate_portfolio_report, simplify_for_user],
        llm=llm,
        verbose=True,
        allow_delegation=False,
        max_iter=3,
    )
