"""
Agent 6: User Advisory Agent
Takes all outputs from agents 2-5 and converts them into a clear,
friendly, actionable report the user can actually understand and act on.
Supports Hindi-English (Hinglish) if needed.
"""

import json


def _generate_portfolio_report(data: str) -> str:
    """Internal report generation (unwrapped for direct use)"""
    try:
        d = json.loads(data) if isinstance(data, str) else data
    except Exception:
        d = {}

    report = """
FD PORTFOLIO OPTIMIZER — YOUR PERSONAL REPORT

PORTFOLIO SUMMARY
=================
This report was generated by analyzing rates, optimizing allocation, and calculating tax.

THE RECOMMENDATION
==================
Book NOW — FD rates are near their cycle peak. 
Locking 12-18 month FDs today captures maximum returns.

YOUR ALLOCATION
===============
Based on PSO optimization, here is your recommended allocation:
"""
    
    # Add allocation table if provided
    if "allocation" in d:
        report += "\nBank Name | Amount | Rate | Maturity\n"
        report += "-" * 50 + "\n"
        for alloc in d.get("allocation", []):
            if alloc.get("weight_percent", 0) > 1:  # Only show >1% allocations
                report += f"{alloc.get('bank_name', 'N/A'):20} | Rs{alloc.get('allocated_amount', 0):,} | {alloc.get('interest_rate', 0):.2f}% | Rs{alloc.get('maturity_amount', 0):,}\n"
    
    # Add summary
    if "summary" in d:
        report += f"\nTotal Investment: Rs{d['summary'].get('total_investment', 0):,}\n"
        report += f"Total Interest Earned: Rs{d['summary'].get('total_interest_earned', 0):,}\n"
        report += f"Total Maturity Amount: Rs{d['summary'].get('total_maturity_amount', 0):,}\n"
        report += f"Expected Annual Return: {d['summary'].get('expected_annual_return_pct', 0):.2f}%\n"
    
    report += """
KEY ACTIONS FOR YOU
===================
1. Book FDs per the allocation above (split across banks as shown)
2. Submit Form 15G at the start of next financial year (April 1)
3. Set calendar reminders for each FD maturity date
4. On maturity, re-evaluate rates — if they've dropped, consider other investments

Next Steps
==========
Walk into any of the listed banks or use their app/Blostem platform to book these FDs today.
"""

    # Include comparator output when available
    if "comparison" in d and d["comparison"]:
        cmp = d["comparison"]
        report += "\n" + cmp.get("table_text", "") + "\n"
        report += cmp.get("recommendation", "") + "\n"

    return report


